import google.generativeai as genai
import os 
from input import user_favorite_books, user_favorite_authors, user_topics_of_interest

genai.configure(api_key='AIzaSyC_VRIjI7lhSRtd3JDJ73tR-7Do3PlS2Po')
generation_config = {"temperature": 0.9, "top_p": 1, "top_k": 1, "max_output_tokens": 2048}

model = genai.GenerativeModel("gemini-pro", generation_config=generation_config)

user_input_prompt = f"Given the favorite books {user_favorite_books} in the style of the author {user_favorite_authors}, recommend the top 10 closest books. Consider topics of interest: {user_topics_of_interest}.Consider books from the following list: 'Iridescent Skin: A Multispecies Journey of White Sharks & Caged humans', 'The Forgotten Palaces of Calcutta', 'Wayel Kati: The Quest of the Seven Guardians', 'Masala and Murder', 'Dala's Street', 'Field Marshal Sam Manekshaw: The Man and His Times', 'Mahanadi: The Tale of a River', 'Preeto & Other Stories: The Male Gaze in Urdu', 'Chai: The Experience of Indian Tea', 'Charu Majumdar: The Dreamer Rebel', 'Soumitra Chatterjee: A Life in Cinema, Theatre, Poetry & Painting', 'Phantom Lovers: Two Novellas', 'Entering the Maze: Queer Fiction of Krishnagopal Mallick', 'Sita Returns: Modern India through Her Eyes', 'A City in the Making: Aspects of Calcutta’s Early Growth', 'Bangladesh War: Report from Ground Zero', 'The Butterfly Effect', 'Jagadish Chandra Bose: The Reluctant Physicist', 'The Aryabhata Clan', 'The Bhagavad Gita: A Life-Changing Conversation', 'The Parrot Green Saree', 'Spellcasters: A Novel', 'Rereading Tagore', 'I, Anupam', 'Zorba the Buddha', 'The Life an Times of David Hare: First Secular Educationist of India', 'Kabulnama', 'Chitra Pothi: Illustrated Palm-Leaf Manuscripts from Orissa', 'The Hungry Stones and Other Stories', 'Rabindranath Tagore: A Pictorial Biography', 'Tracing Marco Polo’s Journey: The Silk Route', 'Sunderbans: The Mystic Mangrove', 'PC Sorcar: The Maharaja of Magic', 'Bengali Culture: Over a Thousand Years', 'Historic Temples in Pakistan: A Call to Conscience', 'Gupp & Gossip: From the Hills', 'Architecture of Santiniketan: Tagore’s Concept of Space', 'Beyond the Himalayas: Journeying Through The Silk Route', 'Indian Classical Dance: The Renaissance and Beyond', 'Jamini Roy: A painter who revisited the roots', 'Dagars and Dhrupad: Divine Legacy', 'A Gift of Grace: The Essence of Guru Nanak’s Spirituality', 'The Little Prince', 'Robinson Crusoe', 'The Wind in the Willows', 'A Dog’s Tale’ and ‘Jungle Stories', 'White & Black: Journey to the Centre of Imperial Calcutta', 'Yatra: An Unfinished Novel'. Suggest 5 books based on the given list, call it localized suggestions and 5 generalized suggestions."
gemini_response = model.generate_content(user_input_prompt)